### ISSUE TITLE
no input for influx db

### ISSUE THREAD

**Issue by smagedy** [dkruyt/ginlong-scraper#1]
Dear dkruyt,
I'm trying to connect my solis inverter to my home assistant with your sraper. I created a new database. But I allways get no information. I allready have 2 other working databases. 
I've changed the input and output in the py file but with no results. I think I'm missing a user and password option in the script. Is this possible or can you help me?

**Comment by dkruyt** [comment]
Did you filled in the username for the ginlong site in the script?

And if you run the script from the commandline, doe you get output like this?

root@grafana:~# /opt/solis-influx/ginlong-scraper.py

Login Succesfull on m.ginlong.com !

Your deviceId is not set, auto detecting
Your deviceId is  somenumber
results from m.ginlong.com

Wed Feb  5 12:34:33 2020

DC_Voltage_PV1: 327.00
DC_Voltage_PV2: 297.00
DC_Current1: 0.40
DC_Current2: 0.40
AC_Voltage: 235.30
AC_Current: 1.40
AC_Power: 241
AC_Frequency: 49.96
DC_Power_PV1: None
DC_Power_PV2: None
Inverter_Temperature: 29.10
Daily_Generation: 1.90
Monthly_Generation: 9.500000000000178
Annual_Generation: 54.099999999999106
Total_Generation: 4520.00
Generation_Last_Month: 42


PVoutput:  OK 200: Added Status

**Comment by smagedy** [comment]
It was a strugle but I finally got it working. I made different changes 
-Some tweaking off the scipt for some small errors
-Created a login for my influxdb. 
-I removed the mqtt output because I get some error's and don't need it. 

I've added my script. 
[ginlong-scraper - github.txt](https://github.com/dkruyt/ginlong-scraper/files/4159896/ginlong-scraper.-.github.txt)
