### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by ghost** [dkruyt/ginlong-scraper#18]
Hi

Thanks for this it looks like a great add on for Grafana.  However, I have a few newbie questions.

1) Which is the device_id on the Solis portal? There are 3 numbers. (1) I think is my account ID. (2) is the inverter serial number and (3) is the logger ID.  Which number to set deviceId to ?

The image may help here.
<img width="1080" alt="Screenshot 2021-03-11 at 21 10 51" src="https://user-images.githubusercontent.com/2766363/110856156-2e250d80-82af-11eb-9005-b5b8228121e7.png">

2) On your main blog page and in the Python script it refers to "deviceId" while on the Github page it refers to "GINLONG_DEVICE_ID", is there a difference?

I am running Grafana, influxDB and your Python script (cron) direct on my server, without Docker.

Edited script to look like this
```
    # solis/ginlong portal config
    username        = 'name@icloud.com'
    password        = 'somepassword'
    domain          = 'm.ginlong.com'
    lan             = '2'
    deviceId        = 'WHICH NUMBER'

    ### Output ###

    # Influx settings
    influx              = 'true'
    influx_database     = 'db_name'
    influx_server       = 'localhost'
    influx_port         = '8086'
    influx_user         = 'name'
    influx_password     = 'password'
    influx_measurement  = 'PV'
```

The Grafana dashboard imported and the data source finds influxDB fine, but there is no data showing.

Thanks in advance for any help you can offer. And sorry for the stupid questions.
Mark

**Comment by ghost** [comment]
I should have said that I am getting this from the script: "2021-03-12 07:05:03,694 ERROR ValueError : No JSON object could be decoded".

**Comment by ghost** [comment]
Closing, I have a different issue now.

**Comment by MetPhoto** [comment]
Closing, I have a different issue now.
