### ISSUE TITLE
Temperature sent to pvoutput is inverter temperature

### ISSUE THREAD

**Issue by JeroenEeuwes** [dkruyt/ginlong-scraper#4]
The temperature sent to pvoutput is the inverter temperature, but I'm pretty sure that field is meant as the outside temperature. Am I wrong or is this on purpose?

**Comment by craigcurtin-dev** [comment]
Pretty sure you are wrong on this one - the inverters only report their own temperatures - no outside temp probes etc

Craig

**Comment by JeroenEeuwes** [comment]
Yes, but my point is that pvoutput can use the temperature field to calculate things like the "Insolation Temperature Coefficient" or it can automatically add the temperature for a system if you tell which weather station to use. This implies that the temperature in pvoutput is either the outside temperature (or perhaps the solar panel temperature). They are not really explicit about it, that's true.

**Comment by craigcurtin-dev** [comment]
Aah right – now I see what you are getting at.

I just have the local BOM (Australian Weather station setup as my location temperature monitor) in PVOutput

There would be no way to get the solar panel temperature unless you had a smart panel that reported it back (I do not think any of them do yet) – so it would be external temp – but with the bigger inverters you would really need to mount the temperature probe remotely so it was not effected by the inverter itself

I think the temp out is just for you to monitor your inverter to make sure it is performing as you expect

**Comment by dkruyt** [comment]
Yes, my mis interpretation, has been removed in the docker version now, thanks for reporting.
