### ISSUE TITLE
Sending to mqtt hangs on updateDate

### ISSUE THREAD

**Issue by JeroenEeuwes** [dkruyt/ginlong-scraper#5]
The script hangs on the mqtt output. In the mqtt topic I could see some of the values. I rearranged the values until I found out the problem was with the updateDate line:

msgs.append((mqtt_topic + "updateDate", int(updateDate), 0, False))

If I commented that line out, it worked OK. I managed to solve this by changing it to this:

msgs.append((mqtt_topic + "updateDate", int(updateDate / 1000 ), 0, False))

I took the cue from the niceTimestamp line:

niceTimestamp = time.ctime((updateDate) / 1000)

**Comment by dkruyt** [comment]
fixed in the docker version now, thanks for reporting.
