### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by kongjudas** [dkruyt/ginlong-scraper#7]
with command:
`root@server:/usr/share/hassio/homeassistant/www# python ginlong-scraper.py`

I get:
```
Traceback (most recent call last):
  File "ginlong-scraper.py", line 2, in <module>
    import requests
ImportError: No module named requests
```

I've falsed both influx and pvoutput, so the only service open is MQTT.

**Comment by craigcurtin-dev** [comment]
Think you will find this is a problem with the URLLIB and URLLIB2 modules not installing correctly.

I suggest you have a look at the Docker version of this script - here

https://hub.docker.com/r/fredericvl/ginlong-solis-scraper

As all the heavy lifting has been done for you - i had it up and running within 1/2 hour today

regards

Craig

**Comment by dkruyt** [comment]
There is now my own docker version, with some fixes and new features. See https://hub.docker.com/r/dkruyt/ginlong-scraper
